//
//  LoginModels.swift
//  Me-cognize
//
//  Created by Hailey on 2023/08/29.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
    // MARK: Use cases
    
    enum Token {
        struct Request {
            let issuer = URL(string: "https://accounts.google.com")!
            let redirectURI = URL(string: AppCredential.shared.redirectURI)!
        }
        
        struct Local {
            let tokens = LocalData.getTokensForTest()
        }
        
        struct Response {
            let accessToken : String
            let refreshToken : String
        }
        
        struct ViewModel {
        }
    }
}
