//
//  LoginInteractor.swift
//  Me-cognize
//
//  Created by Hailey on 2023/08/29.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AppAuth
import GoogleSignIn

protocol LoginBusinessLogic {
    func requestGoogleToken(request: Login.Token.Request, viewController: LoginViewController)
    func requestLocalToken(request: Login.Token.Local)
}

protocol LoginDataStore { }

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    
    func requestGoogleToken(request: Login.Token.Request, viewController: LoginViewController) {
        worker = LoginWorker()
        worker?.getGoogleToken(request: request, viewController: viewController, suceess: { [weak self] in
            self?.presenter?.showHistoryView()
        }, failed: { [weak self] message in
            self?.presenter?.presentError(message)
        })
    }
    
    func requestLocalToken(request: Login.Token.Local){
        AppCredential.shared.set(request.tokens.accessToken, refreshToken: request.tokens.refreshToken)
        self.presenter?.showHistoryView()
    }

}
