//
//  LoginRouter.swift
//  Me-cognize
//
//  Created by Hailey on 2023/08/29.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeToHistory()
}

protocol LoginDataPassing {
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    
  var viewController: LoginViewController?
  var dataStore: LoginDataStore?
    
func routeToHistory() {
      let destinationVC = Util.UI.getViewControllerInStotyBoard(story: "Main", controller: historyviewController.self)
        Util.UI.makeKeyAndVisible(UINavigationController(rootViewController: destinationVC))
  }
}
