//
//  LoginPresenter.swift
//  Me-cognize
//
//  Created by Hailey on 2023/08/29.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func showHistoryView()
    func presentError(_ message: String)
}

class LoginPresenter: LoginPresentationLogic {
    var viewController: LoginDisplayLogic?
    
    func showHistoryView() {
        viewController?.showHistoryView()
    }
    
    func presentError(_ message: String) {
        viewController?.displayError(message)
    }
}
