//
//  HistoryRouter.swift
//  Me-cognize
//
//  Created by Hailey on 2023/08/29.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HistoryRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol HistoryDataPassing {
  var dataStore: HistoryDataStore? { get }
}

class HistoryRouter: NSObject, HistoryRoutingLogic, HistoryDataPassing {
  weak var viewController: historyviewController?
  var dataStore: HistoryDataStore?  

}
