//
//  HistoryPresenter.swift
//  Me-cognize
//
//  Created by Hailey on 2023/08/29.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryPresentationLogic {
    func presentList(response: HistoryModel.List.Response)
}

class HistoryPresenter: HistoryPresentationLogic {
    var viewController: HistoryDisplayLogic?
        
    func presentList(response: HistoryModel.List.Response) {
        let viewModel = HistoryModel.List.ViewModel(historyList: response.historyList)
        viewController?.displayList(viewModel: viewModel)
    }
}
