//
//  AddPresenter.swift
//  Me-cognize
//
//  Created by Hailey on 2023/09/11.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddPresentationLogic {
    func displayAnalyze(response: Add.Send.Response)
    func showAlert(response: Add.Alert.ViewModel)
}

class AddPresenter: AddPresentationLogic {

    
    var viewController: AddDisplayLogic?
    
    func displayAnalyze(response: Add.Send.Response) {
        let viewModel = Add.Send.ViewModel(sentiment: response.documentSentiment)
        viewController?.updateResultData(viewModel: viewModel)
    }
    
    func showAlert(response: Add.Alert.ViewModel){
        viewController?.showAlert(viewModel: response)
    }
}
