//
//  AddRouter.swift
//  Me-cognize
//
//  Created by Hailey on 2023/09/11.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AddDataPassing {
  var dataStore: AddDataStore? { get }
}

class AddRouter: NSObject, AddRoutingLogic, AddDataPassing {
  weak var viewController: AddViewController?
  var dataStore: AddDataStore?
}
